server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/to-do-list
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
