-- CREATE TABLE IF NOT EXISTS CATEGORIES
-- (
--     ID         BIGSERIAL PRIMARY KEY,
--     NAME       VARCHAR(255) NOT NULL UNIQUE,
--     CREATED_AT TIMESTAMP,
--     UPDATED_AT TIMESTAMP
-- );
--
CREATE TABLE IF NOT EXISTS TASKS
(
    ID         BIGSERIAL PRIMARY KEY,
    TITLE       VARCHAR(255) NOT NULL,
    DEADLINE TIMESTAMP,
    IS_DONE BOOLEAN,
    category_id BIGINT NOT NULL,
    FOREIGN KEY (category_id) REFERENCES CATEGORIES(ID),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);